version: '3.7'

services:
  php:
    container_name: php_os
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "88:80"
    depends_on:
      - mysql
    environment:
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_DATABASE: ${DB_DATABASE}
    restart: unless-stopped

  mysql:
    container_name: mysql_os
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_PORT: ${DB_PORT}:3306
    restart: unless-stopped

volumes:
  mysql_data:
